### ISSUE TITLE
compute(list, 0) doesn't work ~3

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-compute#17]
because this check:

```
} else if (args[1]) {
```

is false.

**Comment by ilyavf** [comment]
As far as I can see the following fixes are required for this issue:

**Comment by justinbmeyer** [comment]
@ilyavf could args.length be used?

**Comment by justinbmeyer** [comment]
other than `args.length` ... everything looks good.

**Comment by ilyavf** [comment]
@justinbmeyer: we can use it only if we add a null-check to the loop:
```
	for(var i = 0, arglen = arguments.length; i < arglen; i++) {
		args[i] = arguments[i];
	}
```
I can see sometimes the function gets called with 4 arguments like `[1, undefined, undefined, undefined]`.

**Comment by justinbmeyer** [comment]
> In the very 1st test

Which test does this?  Thanks!

**Comment by ilyavf** [comment]
@justinbmeyer this one (along with some other):
```
test('single value compute', function () {
	var num = compute(1);
	num.on('change', function (ev, newVal, oldVal) {
		equal(newVal, 2, 'newVal');
		equal(oldVal, 1, 'oldVal');
	});
	num(2);
});
``
![image](https://cloud.githubusercontent.com/assets/1895948/18328367/7e8a497a-751c-11e6-8203-065193f40ce3.png)

**Comment by ilyavf** [comment]
Basically [here](https://github.com/canjs/can-compute/blob/master/can-compute.js#L26)
```
var internalCompute = new Compute(getterSetter, context, eventName, bindOnce);
```

**Comment by ilyavf** [comment]
@justinbmeyer Is there anything wrong with the above?
For the current issue I would just check args[1], not args.length.

**Comment by justinbmeyer** [comment]
@ilyavf Yarg.   I'm pretty sure future versions of JS have fixed this with some way of calling new with arbitrary arguments.  I think what you suggest is fine.

**Comment by justinbmeyer** [comment]
@ilyavf this is solved right?

**Comment by ilyavf** [comment]
@justinbmeyer Sorry, got busy with client's work.
Yes, this is done, and I see its already merged to master. Closing then.
