### ISSUE TITLE
Compute that will be updated by a future batch is not updated on a read

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-compute#32]
The following breaks

```js
test("Reading a compute before the batch has completed (#32)", function(){
	var c1 = compute(1),
		c2;
	c1.on("change", function(){
		equal(c2(),4, "updated");
	});

	c2 = compute(function(){
		return c1() * c1();
	});

	c2.on("change", function(){});

	c1(2);
});
```

Is this something we should fix?  We can make people use `batch.after` to be notified when the current batch has completed and all computes should be updated.

It might be possible to create a `flush` that computes could call when being read.

**Comment by justinbmeyer** [comment]
The following breaks

```js
test("Reading a compute before the batch has completed (#32)", function(){
	var c1 = compute(1),
		c2;
	c1.on("change", function(){
		equal(c2(),4, "updated");
	});

	c2 = compute(function(){
		return c1() * c1();
	});

	c2.on("change", function(){});

	c1(2);
});
```

Is this something we should fix?  We can make people use `batch.after` to be notified when the current batch has completed and all computes should be updated.

It might be possible to create a `flush` that does this too.

**Comment by justinbmeyer** [comment]
cc @Macrofig .. this is related to a problem you've encountered in the past.

**Comment by matthewp** [comment]
So the problem is that c2 isn't recomputed until after the c1 change event occurs?

If so, I think I lean towards fixing it. If a compute is being read and is in queue to be recomputed, go ahead and recompute it.

**Comment by justinbmeyer** [comment]
It's not in the queue yet.

**Comment by justinbmeyer** [comment]
closed by : 
https://github.com/canjs/can-event/pull/19

and 

https://github.com/canjs/can-observation/pull/18
