### ISSUE TITLE
`compute( object, propertyName [, eventName] )` not working

### ISSUE THREAD

**Issue by BigAB** [canjs/can-compute#35]
https://jsbin.com/nazoxun/edit?js,output

`compute( object, propertyName [, eventName] )` appears to not be working correctly.

Not sure if i am doing something wrong in the jsbin, but it appears to just not update

**Comment by matthewp** [comment]
Think it's a bug, investigating.

**Comment by matthewp** [comment]
Just released a pre.16 and it's fixed now: https://jsbin.com/hecizaqisi/1/edit?html,js,output

**Comment by imjoshdean** [comment]
This is broke again in 3.0.10, you aren't able to set the value.

![image](https://user-images.githubusercontent.com/252054/27343940-2b0f1a54-55aa-11e7-930e-5f0a97244331.png)

**Comment by matthewp** [comment]
Underlying issue: https://github.com/canjs/can-compute/issues/84

Will fix there.
