### ISSUE TITLE
Nested instantiated computes do not update the outer compute ~12

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-compute#7]
From: https://github.com/canjs/canjs/issues/1394

Example:  http://justinbmeyer.jsbin.com/tinece/5/edit?html,js,output

```
        var inside;
        var outside = can.compute(function(){
            inside = can.compute();
            return inside()
        })

        outside.bind('change', function(ev, newVal){
            console.log("changed");
        });
        inside(4);
```

**Comment by imaustink** [comment]
I went over this with @phillipskevin and it seems everything is working properly. The reason this example doesn't work is that when `inside` is set, `outside` is recomputed and `inside` is overwritten by a new `compute`.

The following example works:
```javascript
var inside;

var outside = compute(function(){
	if (!inside) {
		inside = compute('foo');
	}
	return inside();
});

outside.on('change', function(ev, newVal){
	equal(newVal, 'bar');
});
inside('bar');
```
